name: Terraform Import and Apply ..

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}'

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: terraform -chdir=terraform init -backend-config="resource_group_name=github-terraform-rg1" \
              -backend-config="storage_account_name=storagegithubtf" \
              -backend-config="container_name=tfstate" \
              -backend-config="key=terraform.tfstate"
        working-directory: terraform

#      - name: Terraform Import1
#        env:
#          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#        run: terraform import azurerm_resource_group.rg /subscriptions/9bf7ac78-0625-49e4-9fe2-4f36dd943a48/resourceGroups/github-terraform-rg1
#        working-directory: terraform
#
#      - name: Terraform Init
#        env:
#          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#        run: terraform init
#        working-directory: terraform
#
#      - name: Terraform Import2
#        env:
#          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#        run: terraform import azurerm_storage_account.STA /subscriptions/9bf7ac78-0625-49e4-9fe2-4f36dd943a48/resourceGroups/github-terraform-rg1/providers/Microsoft.Storage/storageAccounts/storagegithubtf
#        working-directory: terraform

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: terraform destroy
        working-directory: terraform

